ENT.Type = "anim"
ENT.Base = "q1_pickup_base"
ENT.PrintName = "Armor Base"
ENT.Category = "Quake 1"
ENT.Author = "Upset"
ENT.Contact = ""
ENT.Purpose = ""
ENT.Instructions = ""
ENT.Spawnable = false
ENT.AdminOnly = false