ENT.Type = "anim"
ENT.Base = "q1_powerup_base"
ENT.PrintName = "Quad Damage"
ENT.Category = "Quake Powerups"
ENT.Author = "Upset"
ENT.Contact = ""
ENT.Purpose = ""
ENT.Instructions = ""
ENT.Spawnable = true
ENT.AdminOnly = true