ENT.Type = "anim"
ENT.PrintName = "Health Small"
ENT.Base = "q1_health_base"
ENT.Category = "Quake 1"
ENT.Author = "Upset"
ENT.Contact = ""
ENT.Purpose = ""
ENT.Instructions = ""
ENT.Spawnable = true
ENT.AdminOnly = true