ENT.Type = "anim"
ENT.Base = "q1_pickup_base"
ENT.PrintName = "Super Nailgun"
ENT.Category = "Quake 1"
ENT.Author = "Upset"
ENT.Contact = ""
ENT.Purpose = ""
ENT.Instructions = ""
ENT.Spawnable = true
ENT.AdminOnly = true
ENT.AdminSpawnable = true