game.AddParticles( "particles/hardlight_fx.pcf" )
PrecacheParticleSystem("Hardlight_Arc")
PrecacheParticleSystem("Hardlight_Arc1")
PrecacheParticleSystem("Hardlight_Arc2")
PrecacheParticleSystem("Hardlight_Arc3")
PrecacheParticleSystem("Hardlight_Arc4")
PrecacheParticleSystem("Hardlight_Solar")
PrecacheParticleSystem("Hardlight_Solar1")
PrecacheParticleSystem("Hardlight_Solar2")
PrecacheParticleSystem("Hardlight_Solar3")
PrecacheParticleSystem("Hardlight_Solar4")
PrecacheParticleSystem("Hardlight_Void")
PrecacheParticleSystem("Hardlight_Void1")
PrecacheParticleSystem("Hardlight_Void2")
PrecacheParticleSystem("Hardlight_Void3")
PrecacheParticleSystem("Hardlight_Void4")
