ENT.Type = "anim"
ENT.PrintName = "Cells (Big)"
ENT.Base = "q1_ammo_base"
ENT.Category = "Quake 1 Ammo"
ENT.Author = "Upset"
ENT.Contact = ""
ENT.Purpose = ""
ENT.Instructions = ""
ENT.Spawnable = true
ENT.AdminOnly = true
ENT.AdminSpawnable = true